spring:
  application:
    name: provider
server:
  port: 8081

dubbo:
 application:
  name: dubbo-provider #??????
 protocol:
  name: dubbo #????
  port: -1 #???-1???????????????
 registry:
  address: zookeeper://127.0.0.1:2181 #???????????zookeeper??????????????
  timeout: 60000 #????????????10S?????????????????5s
